  sudo: required
  services:
    - postgresql
    - rabbitmq
  env:
    - BRIGHTER_MESSAGE_STORE_URL="postgresql://postgres:@localhost/travis_ci_test"
  language: python
  python:
    - "3.6"
  cache: pip
  install:
    - pip install pipenv && pipenv install -e . && pipenv install --dev
  before_script:
    - psql -c 'create database travis_ci_test;' -U postgres
  script:
    - python testrunner.py
    
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/f69a76bc337b9bbeb66e
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
